spring:
  config:
    activate:
      on-profiles: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to UdemyBank accounts related QA APIs "
  contactDetails:
    name: "Bob Ray - QA Lead"
    email: "Bob@udemy.com"
  onCallSupport:
    - (666) 123-3214
    - (666) 123-4321
