server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#     active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
##         search-locations: "file:///Users//lambui//Documents//config"
        git:
          uri: "https://github.com/thanhlam1211/lambui-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest_"_

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:
#      enabled: true
#  endpoint:
#    health:
#      probes:
#        enabled: true
#
encrypt:
#  complex key random, can be any value
  key: "5F82B5324EEA78672B6D2D89DBDB2"
